best_checkpoint_metric: molecule_stability
best_checkpoint_mode: max
checkpoint_path: null
dataloader:
  each_prompt_sample: 8
  epoches: 1
  micro_batch_size: 16
  sample_group_size: 1
  smiles_path: /nfs/roberts/project/pi_mg269/yl2428/e3_diffusion_for_molecules-main/qm9/temp/qm9_smiles.pickle
model:
  config: /nfs/roberts/project/pi_mg269/yl2428/e3_diffusion_for_molecules-main/pretrained/edm/edm_qm9/args.pickle
  model_path: /nfs/roberts/project/pi_mg269/yl2428/e3_diffusion_for_molecules-main/pretrained/edm/edm_qm9/generative_model_ema.npy
  share_initial_noise: false
  time_step: 10
name: edm
resume: false
reward:
  energy_transform_offset: 10000.0
  energy_transform_scale: 1000.0
  energy_weight: 1.0
  force_clip_threshold: null
  force_weight: 1.0
  mlff_model: uma-s-1p1
  shaping:
    enabled: false
    gamma: 1.0
    horizon: 200
    max_atoms_per_call: 200000
    method: potential
    scheduler:
      adaptive:
        coarse_stride: 10
        fine_stride: 2
        threshold_fraction: 0.25
      include_terminal: true
      mode: adaptive
      skip_prefix: 500
      uniform_stride: 1
    terminal_weight: 5
    weight: 1.0
  type: uma
  use_energy: false
save_path: null
seed: 42
train:
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-08
  adam_weight_decay: 0.0001
  adv_clip_max: 5
  clip_range: 0.15
  force_alignment_enabled: false
  force_alignment_min_delta: 0.0001
  force_alignment_min_force: 0.0001
  force_alignment_weight: 0.5
  learning_rate: 5.0e-06
  max_grad_norm: 1
  scheduler:
    min_lr_ratio: 0.1
    name: cosine
    num_cycles: 0.5
    stable_ratio: 0.9
    total_steps: null
    warmup_steps: 10
  train_micro_batch_size: 16
wandb:
  enabled: false
  wandb_name: edm-ddp-run
  wandb_project: ddpo
